### ISSUE TITLE
Google fonts title

### ISSUE THREAD

**Issue by rzmk** [rzmk/mega-todo#2]
Find a font from [Google Fonts](https://fonts.google.com/) and import it into the project. Then, set all `h1` elements to that font.

Bonus: Find a font for the table header `th` text too.

**Comment by github4maninder** [comment]
Hi, I would like to work on this request. assign this to me.

**Comment by rzmk** [comment]
Sounds great, give it a go! 👍

**Comment by github4maninder** [comment]
Created a PR, let me know if I need to make any changes. thanks

**Comment by rzmk** [comment]
Issue resolved in #7 by @github4maninder. Great work! 👏
