### ISSUE TITLE
Delete table row functionality.

### ISSUE THREAD

**Issue by rzmk** [rzmk/mega-todo#21]
Add a way to delete inserted rows (i.e. a column to delete new entries on the right with a delete icon/emoji like ❌).

**Comment by ishaanbedi** [comment]
Hi! Should the ❌ emoji delete all the rows or just the last (recent) one?

**Comment by rzmk** [comment]
Each inserted row should have its own ❌ so that when clicked it gets deleted from the table while the rest of the rows remain with their own ❌ until clicked.

**Comment by rzmk** [comment]
Requirement added: Must alter localStorage and work correctly.
