### ISSUE TITLE
Too many <th>!

### ISSUE THREAD

**Issue by rzmk** [rzmk/mega-todo#5]
Looks like our code is a bit unconventional! We need to change all the `<th>` tags in the **non-header row** to `<td>`. Use the examples here as a reference for your PR (Pull Request): https://www.w3schools.com/html/html_tables.asp

**Comment by ishaanbedi** [comment]
Hey! I'd like to work on this issue! 
Can you assign it to me?

**Comment by rzmk** [comment]
Sounds great @ishaanbedi, give it a go! 👍

**Comment by ishaanbedi** [comment]
Hi! I am working on it but while going through the webpage, I can see there is no option to add item to the todo list. 
Can you elaborate the feature ?

**Comment by rzmk** [comment]
Adding new todos is for issue #3. 

For now, the idea is to have a simple "Add Todo" button below the bottom-most row that when clicked will create a new row in the table based on the default row values.

**Comment by ishaanbedi** [comment]
Okay! Rely on me. I'll deliver it with the same feature.

**Comment by rzmk** [comment]
Thank you! No rush. 👍

**Comment by ishaanbedi** [comment]
Hi! I have raised the pull request! Kindly check it.
